const $ = (id) => document.getElementById(id);
const base = $("base"), health = $("health"), message = $("message");
let taskTimer = null;
base.value = sessionStorage.getItem("agentBase") || location.origin;
function apiUrl(path) { const root=base.value.trim().replace(/\/$/,""); if(!/^https?:\/\//i.test(root)) throw new Error("API base must start with http:// or https://"); return root+path; }
function setMessage(text,error=false){message.textContent=text;message.className=error?"message error":"message";}
async function checkHealth(){try{const r=await fetch(apiUrl("/health"),{cache:"no-store"});const d=await r.json();health.textContent=r.ok?"online":"error";health.dataset.state=r.ok?"ok":"error";return r.ok&&d.status==="ok";}catch(e){health.textContent="offline";health.dataset.state="error";return false;}}
$("pair").onclick=async()=>{try{const secret=prompt("Enter the Agent API secret for this one-time pairing:");if(!secret) return;const r=await fetch(apiUrl("/pair"),{method:"POST",headers:{Authorization:"Bearer "+secret},credentials:"include"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Pairing failed.");setMessage("Browser paired. The secret was not stored.");}catch(e){setMessage(e.message,true);}};
$("logout").onclick=async()=>{try{await fetch(apiUrl("/logout"),{method:"POST",credentials:"include"});setMessage("Session ended.");}catch(e){setMessage(e.message,true);}};
async function startTask(){try{const goal=$("goal").value.trim(),max_steps=Number($("steps").value);if(!goal)throw new Error("Enter a goal.");const r=await fetch(apiUrl("/tasks"),{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({goal,max_steps})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Task submission failed.");$("taskCard").classList.remove("hidden");$("taskId").textContent=d.task_id;setMessage("Task started.");pollTask(d.task_id);}catch(e){setMessage(e.message,true);}}
async function pollTask(taskId){clearTimeout(taskTimer);try{const r=await fetch(apiUrl("/tasks/"+encodeURIComponent(taskId)),{credentials:"include",cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Task lookup failed.");$("status").textContent=d.status;$("step").textContent=String(d.current_step??"-")+" / "+String(d.max_steps??"-");$("verified").textContent=d.verified?"yes":"no";$("history").textContent=JSON.stringify(d.history||[],null,2);if(d.status==="running"||d.status==="pending")taskTimer=setTimeout(()=>pollTask(taskId),1200);else setMessage("Task "+d.status+".");}catch(e){setMessage(e.message,true);taskTimer=setTimeout(()=>pollTask(taskId),2500);}}
$("run").onclick=startTask;checkHealth();
